module.exports = {
  // App settings
  SALT_ROUNDS: 10,
  PORT: process.env.PORT || 4000,

  // User Types
  USER_TYPE_ADMIN: 1,
  USER_TYPE_RECRUITER: 2,
  USER_TYPE_CANDIDATE: 3,

  // Career Levels
  CAREER_ENTRY_LEVEL: 1,
  CAREER_MID_LEVEL: 2,
  CAREER_SENIOR_LEVEL: 3,
  CAREER_EXECUTIVE_LEVEL: 4,

  // Employment Types
  EMPLOYMENT_FULLTIME: 1,
  EMPLOYMENT_PARTTIME: 2,
  EMPLOYMENT_REMOTE: 3,
  EMPLOYMENT_CONTRACT: 4,
  EMPLOYMENT_INTERNSHIP: 5,
  EMPLOYMENT_TRAINING: 6,
  // Application Statuses
  APPLICATION_STATUS_APPLIED: 1,

  // Transaction Statuses
  TRANSACTION_STATUS_STARTED: 1,
  TRANSACTION_STATUS_PAID: 2,
  TRANSACTION_STATUS_REJECTED: 3,
  TRANSACTION_STATUS_REFUNDED: 4,

  // Payment Types
  PAYMENT_TYPE_VISA_MASTER: 1,
  PAYMENT_TYPE_IDEAL: 2,
  PAYMENT_TYPE_PAYPAL: 3,

  // Package Configs
  PACKAGE_FREE: {
    jobLimit: 2,
    durationInMonths: 1,
  },
  PACKAGE_PREMIUM: {
    jobLimit: 20,
    durationInMonths: 12,
  },
};
